learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),   # blank string is referring to the local host 8000 page - base url
]

learning_log/learning_logs/urls.py
"""Defines URL patterns for learning_logs"""

from django.urls import path   # path is needed to map urls to views
from . import views   # from same directory import the views module (this is what the '.' means

app_name = 'learning_logs'
urlpatterns = [              # app_name and urlpatterns should always be nammed like that as variable names
    # Home Page
    path('', views.index, name='index'),    # the empty string always matches the base url, localhost 8000
    # Page that shows all topics
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Page for adding a new Topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

learning_log/users/urls.py
"""Defines URL patterns for users app"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # include the default authorization url from django
    path('', include('django.contrib.auth.urls')),
    # Registration page
    path('register/', views.register, name='register'),
]

learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """A topic the user is learning about"""

    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)   # define that each topic belongs to a single user

    def __str__(self):
        """Return a string representation of the model"""

        return self.text


class Entry(models.Model):
    """Something specific learned about a topic"""

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model"""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return f"{self.text}"

learning_log/users/models.py
from django.db import models

# Create your models here.

learning_log/learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}   # override django's default settings to increase the number of columns in the text area

learning_log/learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
    """The home page view for learning log"""

    return render(request, 'learning_logs/index.html')

@login_required    # a decorator for the topics function
def topics(request):
    """Show all topics"""

    topics = Topic.objects.filter(owner=request.user).order_by('date_added')  # filter shows only the user's topics
    context = {'topics': topics}

    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries"""
    topic = Topic.objects.get(id=topic_id)   # this is a querry

    # make sure that the topic belongs to the current user
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')   # minus used for reverse order
    context = {"topic": topic, 'entries': entries}

    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """add a new topic"""

    if request.method != 'POST':
        # means no data submitted so you just show a blank form
        form = TopicForm()
    else:
        # POST data submitted and process it
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user   # associate the new topic to the user
            new_topic.save()
            return redirect('learning_logs:topics')  # after submission get redirected to your topics

    # display a blank or invalid form to be sent to the template
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """add a new entry"""

    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # means no data submitted so you just show a blank form
        form = EntryForm()
    else:
        # POST data submitted and process it
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)   # dont save to the database yet
            new_entry.topic = topic
            new_entry.save()   # now save it together with its topic
            return redirect('learning_logs:topic', topic_id = topic_id)

    # display a blank or invalid form to be sent to the template
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """edit an entry"""

    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # means no data submitted so you just show the previous instance of the form
        form = EntryForm(instance=entry)
    else:
        # POST data submitted and process it
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id = topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

learning_log/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Register a new user"""

    if request.method != 'POST':
        # Display blank registration form
        form = UserCreationForm()
    else:
        # Process completed form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # log the user in and redirect to the homepage
            login(request, new_user)
            return redirect('learning_logs:index')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>

<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

      <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
              aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-togler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
              </li>
          </ul>

          <ul class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text">Hello, {{ user.username }}!</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                </li>
              {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                </li>
              {% endif %}
          </ul>
      </div>
  </nav>

  <main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom">
          {% block page_header %}{% endblock page_header %}
      </div>
      <div>
          {% block content %}{% endblock content %}
      </div>
  </main>

</body>
</html>

learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
{% endblock page_header %}

{% block content %}

  <p>Edit entry:</p>

  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Save changes</button>
    {% endbuttons %}
  </form>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <div class="jumbotron">
    <h1 class="display-3">Track your learning!</h1>

    <p class="lead">Make your own Learning Log, and keep a list of the topics your are learning about.
      Whenever you learn something new about a topic, make an entry to summarize what you've learned!</p>
    {% if not user.is_authenticated %}
      <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">
        I'm in! Where do I register? &raquo;
      </a>
    {% else %}
      <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:new_topic' %}" role="button">
        Start a new topic &raquo;
      </a>
      <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:topics' %}" role="button">
        View your topics &raquo;
      </a>
    {% endif %}
  </div>
{% endblock page_header %}

learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
{% endblock page_header %}

{% block content %}

  <p>Add a new entry:</p>

  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Add entry</button>
    {% endbuttons %}
  </form>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}


{% block content %}
  <p>Add the topic name:</p>

  <form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Add topic</button>
    {% endbuttons %}
  </form>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}

  <p>
      <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>
  <ul>
      {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ entry.date_added|date:'M d, Y H:i' }}
                <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a> </small>
            </h4>
            <div class="card-body">
                {{ entry.text|linebreaks  }}
            </div>
        </div>
      {% empty %}
        <p>There are no entries for this topic yet.</p>
      {% endfor %}
  </ul>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}

{% block content %}

  <ul>
      {% for topic in topics %}
        <div class="card mb-3">
            <h3 class="card-header">
                <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
                <small>         Added on {{ topic.date_added|date:'M d, Y' }}</small>
            </h3>
        </div>
      {% empty %}
      <li><h3>No topics have been added yet.</h3></li>
      {% endfor %}
  </ul>

  <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:new_topic' %}" role="button">Add a new topic</a>

{% endblock content %}